// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" xorm:"-" redis:"-"`
	XXX_unrecognized     []byte   `json:"-" xorm:"-" redis:"-"`
	XXX_sizecache        int32    `json:"-" xorm:"-" redis:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" xorm:"-" redis:"-"`
	XXX_unrecognized     []byte   `json:"-" xorm:"-" redis:"-"`
	XXX_sizecache        int32    `json:"-" xorm:"-" redis:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type User struct {
	// @inject_tag: xorm:"'id' not null pk autoincr" redis:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" xorm:"'id' not null pk autoincr" redis:"id"`
	// @inject_tag: xorm:"'user_name' varchar(30) not null default ''" redis:"username"
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty" xorm:"'user_name' varchar(30) not null default ''" redis:"username"`
	// @inject_tag: xorm:"'email' varchar(30) not null default ''" redis:"email"
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty" xorm:"'email' varchar(30) not null default ''" redis:"email"`
	// @inject_tag: xorm:"'password' varchar(30) not null default ''" redis:"password"
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty" xorm:"'password' varchar(30) not null default ''" redis:"password"`
	// @inject_tag: xorm:"'created_at' created"
	Created int64 `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty" xorm:"'created_at' created"`
	// @inject_tag: xorm:"'updated_at' updated"
	Updated int64 `protobuf:"varint,6,opt,name=updated,proto3" json:"updated,omitempty" xorm:"'updated_at' updated"`
	// @inject_tag: xorm:"'deleted_at' deleted"
	Deleted              int64    `protobuf:"varint,7,opt,name=deleted,proto3" json:"deleted,omitempty" xorm:"'deleted_at' deleted"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" xorm:"-" redis:"-"`
	XXX_unrecognized     []byte   `json:"-" xorm:"-" redis:"-"`
	XXX_sizecache        int32    `json:"-" xorm:"-" redis:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *User) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *User) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

type RegisterResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Affected             int64    `protobuf:"varint,3,opt,name=affected,proto3" json:"affected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" xorm:"-" redis:"-"`
	XXX_unrecognized     []byte   `json:"-" xorm:"-" redis:"-"`
	XXX_sizecache        int32    `json:"-" xorm:"-" redis:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisterResponse) GetAffected() int64 {
	if m != nil {
		return m.Affected
	}
	return 0
}

type UserInfoResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *User    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" xorm:"-" redis:"-"`
	XXX_unrecognized     []byte   `json:"-" xorm:"-" redis:"-"`
	XXX_sizecache        int32    `json:"-" xorm:"-" redis:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (m *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(m, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserInfoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserInfoResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "user.LoginResponse")
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*RegisterResponse)(nil), "user.RegisterResponse")
	proto.RegisterType((*UserInfoResponse)(nil), "user.UserInfoResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xcd, 0x4a, 0xf4, 0x30,
	0x14, 0x9d, 0x76, 0x3a, 0x3f, 0xdf, 0x9d, 0x4f, 0x19, 0xa2, 0x48, 0x99, 0x85, 0x48, 0x56, 0x82,
	0x30, 0x48, 0x7d, 0x01, 0xb7, 0x82, 0xab, 0x8a, 0x3b, 0x17, 0xc6, 0xe6, 0xb6, 0x04, 0xa6, 0x4d,
	0x4d, 0x5a, 0x7d, 0x22, 0x5f, 0xc0, 0x27, 0x94, 0x9b, 0xb4, 0x75, 0x3a, 0xe8, 0xc6, 0x5d, 0x4e,
	0x4e, 0xce, 0xc9, 0x39, 0x37, 0x01, 0x68, 0x2d, 0x9a, 0x6d, 0x6d, 0x74, 0xa3, 0x59, 0x44, 0x6b,
	0x7e, 0x0b, 0xff, 0xef, 0x75, 0xa1, 0xaa, 0x14, 0x5f, 0x5b, 0xb4, 0x0d, 0x3b, 0x85, 0x19, 0x96,
	0x42, 0xed, 0xe2, 0xe0, 0x22, 0xb8, 0xfc, 0x97, 0x7a, 0xc0, 0x36, 0xb0, 0xac, 0x85, 0xb5, 0xef,
	0xda, 0xc8, 0x38, 0x74, 0xc4, 0x80, 0xf9, 0x15, 0x1c, 0x75, 0x0e, 0xb6, 0xd6, 0x95, 0x45, 0x3a,
	0x4c, 0xd6, 0x95, 0x28, 0xb1, 0x73, 0x19, 0x30, 0xff, 0x0c, 0x20, 0x7a, 0xb4, 0x68, 0xd8, 0x31,
	0x84, 0x4a, 0x3a, 0x7a, 0x9a, 0x86, 0x4a, 0x8e, 0x44, 0xe1, 0x58, 0xf4, 0x9d, 0x69, 0xfa, 0x5b,
	0xa6, 0x68, 0x9c, 0x89, 0xc5, 0xb0, 0xc8, 0x0c, 0x8a, 0x06, 0x65, 0x3c, 0x73, 0x57, 0xf4, 0x90,
	0x98, 0xb6, 0x96, 0x8e, 0x99, 0x7b, 0xa6, 0x83, 0xc4, 0x48, 0xdc, 0x21, 0x31, 0x0b, 0xcf, 0x74,
	0x90, 0x3f, 0xc1, 0x3a, 0xc5, 0x42, 0xd9, 0x06, 0xcd, 0x50, 0x92, 0x41, 0x94, 0x69, 0x89, 0x5d,
	0x03, 0xb7, 0x26, 0x87, 0x12, 0xad, 0x15, 0x45, 0x5f, 0xa1, 0x87, 0x94, 0x55, 0xe4, 0x39, 0x66,
	0x64, 0x3e, 0x75, 0x8a, 0x01, 0xf3, 0x67, 0x58, 0xd3, 0x44, 0xee, 0xaa, 0x5c, 0xff, 0xd1, 0xfd,
	0x1c, 0x22, 0x29, 0x1a, 0xe1, 0x9c, 0x57, 0x09, 0x6c, 0xdd, 0x23, 0x93, 0x67, 0xea, 0xf6, 0x93,
	0x8f, 0x00, 0x56, 0x04, 0x1f, 0xd0, 0xbc, 0xa9, 0x0c, 0x59, 0x02, 0x33, 0xf7, 0x62, 0x8c, 0xf9,
	0xa3, 0xfb, 0x1f, 0x60, 0x73, 0x32, 0xda, 0xf3, 0x79, 0xf8, 0x84, 0x5d, 0xc3, 0xb2, 0x9f, 0x01,
	0xdb, 0xbb, 0x61, 0x73, 0xe6, 0xd7, 0x87, 0xf3, 0xf1, 0x8a, 0xbe, 0xd7, 0x4f, 0x8a, 0xc3, 0xce,
	0x7c, 0xf2, 0x32, 0x77, 0x1f, 0xf3, 0xe6, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x34, 0x2d, 0xc8,
	0xa6, 0x02, 0x00, 0x00,
}
